### ISSUE TITLE
我想问下，MTCNN做检测的时候会不会出现误检测

### ISSUE THREAD

**Issue by KaiJin1995** [shanren7/real_time_face_recognition#3]
我最近移植了MTCNN，发现很容易就把不是人的物体也给框了起来，不知道你有没有出现或者解决这个问题

**Comment by aixiamomo** [comment]
遇到了和你一样的情况，不知道如何解决

**Comment by lizhili** [comment]
@KaiJin1995 @aixiamomo 能否把你们出现错误的照片贴出来？

**Comment by KaiJin1995** [comment]
当时是增大阈值就可以解决这个问题了
